#!/bin/bash

echo "starting ssh"
eval $(ssh-agent)
echo "starting user dbus"
export $(dbus-launch --exit-with-session)
echo "starting mpd"
mpd &
echo "mpd" > ~/.cache/current_player
mpDris2 &
echo "starting pipewire"
pipewire &
pipewire-pulse &
export _JAVA_AWT_WM_NONREPARENTING=1
exec Hyprland >> ~/.hyprland/stdout 2>> ~/.hyprland/stderr
