#!/bin/sh
dmenu="dmenu -l 10 -c -n -fn Hack-14 "

playerctl -a pause
for p in $(playerctl -l);do
	choices=$choices"$(playerctl -p $p metadata title)\n";
done

choice=$(echo $choices | head -c -2 | $dmenu)
for p in $(playerctl -l);do
	if [ "$(playerctl -p $p metadata title)" = "$choice" ] ; then
		player=$p
	fi
done

if [ $player ];then
echo $player > ~/.cache/current_player
fi
~/.bin/cache_spotifyd.sh &

